---
horizon_url: "http://9.30.217.9"

auth: {
  auth_url: "http://9.30.217.9:5000/v3",
  username: "demo",
  password: "{{ password }}",
  domain_name: "default",
  project_name: "demo"
}

app_env: {
  image_name: "ubuntu-15.04",
  region_name: "RegionOne",
  availability_zone: "nova",
  validate_certs: False,
  ssh_user: "ubuntu",
  private_net_name: "Bluebox",
  flavor_name: "m1.small",
  public_key_file: "/home/tong/.ssh/id_rsa.pub",
  stack_size: 4,
  volume_size: 2,
  block_device_name: "/dev/vdb",
  wp_theme: "https://downloads.wordpress.org/theme/iribbon.2.0.65.zip",
  wp_posts: "http://wpcandy.s3.amazonaws.com/resources/postsxml.zip"
}
