---
horizon_url: "https://cloud1.osic.org"

auth: {
  auth_url: "https://cloud1.osic.org:5000/v3",
  username: "litong01",
  password: "{{ password }}",
  domain_name: "default",
  project_name: "interop_challenge"
}

app_env: {
  image_name: "ubuntu-server-14.04",
  region_name: "",
  availability_zone: "nova",
  validate_certs: True,
  private_net_name: "interopnet",
  flavor_name: "m1.small",
  public_key_file: "/home/tong/.ssh/id_rsa.pub",
  stack_size: 4,
  volume_size: 2,
  block_device_name: "/dev/vdb",
  wp_theme: "https://downloads.wordpress.org/theme/iribbon.2.0.65.zip",
  wp_posts: "http://wpcandy.s3.amazonaws.com/resources/postsxml.zip"
}
