---
#   Copyright Red Hat, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.
#

horizon_url: "https://x86.trystack.org/dashboard/"

auth: {
  auth_url: "http://8.43.86.11:5000/v3",
  username: "{{ lookup('env', 'OS_USERNAME') }}",
  password: "{{ lookup('env', 'OS_PASSWORD') }}",
  project_name: "{{ lookup('env', 'OS_PROJECT_NAME') }}",
  domain_name: "default",
}

app_env: {
  ssh_user: "ubuntu",
  image_name: "ubuntu1404",
  region_name: "regionOne",
  availability_zone: "nova",
  validate_certs: False,
  private_net_name: "private",
  flavor_name: "m1.small",
  public_key_file: "/root/.ssh/id_rsa.pub",
  stack_size: 4,
  volume_size: 2,
  block_device_name: "/dev/vdb",
  wp_theme: "https://downloads.wordpress.org/theme/iribbon.2.0.65.zip",
  wp_posts: "http://wpcandy.s3.amazonaws.com/resources/postsxml.zip"
}