---
- name: Remove security group
  os_security_group:
    state: absent
    auth: "{{ auth }}"
    region_name: "{{ app_env.region_name }}"
    availability_zone: "{{ app_env.availability_zone }}"
    validate_certs: "{{ app_env.validate_certs }}"
    name: dockerswarm_sg
    description: secuirty group for dockerswarm

- name: Delete discovery url directory
  file: path="/tmp/{{ env }}" state=absent

- name: Delete a key-pair
  os_keypair:
    state: absent
    auth: "{{ auth }}"
    region_name: "{{ app_env.region_name }}"
    availability_zone: "{{ app_env.availability_zone }}"
    validate_certs: "{{ app_env.validate_certs }}"
    name: "dockerswarm"

- debug:
    msg: >-
      The work load test started at {{ starttime.time }},
      ended at {{ ansible_date_time.time }}